name: Docker Image CI

on:
  push:
    branches: ["staging"]

env:
  IMAGE_NAME: flex-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/$(echo $IMAGE_NAME)
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USER }}/$(echo $IMAGE_NAME)