name: Docker Image CI

on:
  push:
    branches: ["staging"]

env:
  IMAGE_NAME: flex-api
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  PORT: ${{secrets.PORT}}
  API_TYPE: ${{secrets.API_TYPE}}
  API_UPLOAD: ${{secrets.API_UPLOAD}}
  DB_HOST: ${{secrets.DB_HOST}}
  DB_NAME: ${{secrets.DB_NAME}}
  DB_PORT: ${{secrets.DB_PORT}}
  DB_USER: ${{secrets.DB_USER}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  BCRYPT_SALT_ROUNDS: ${{secrets.BCRYPT_SALT_ROUNDS}}
  AES_SECRET_IV: ${{secrets.AES_SECRET_IV}}
  AES_SECRET_KEY: ${{secrets.AES_SECRET_KEY}}
  JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Declare ENV
        run: echo "Build environment port $PORT"
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/$(echo $IMAGE_NAME)
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USER }}/$(echo $IMAGE_NAME)
